<?php

/**
 * @file
 * Defines an arithmetic field type.
 */

/**
 * Implements hook_field_formatter_info_alter().
 */
function arithmetic_field_field_formatter_info_alter(&$info) {
  if (isset($info['number_decimal'])) {
    $info['number_decimal']['field_types'][] = 'arithmetic';
  }
  if (isset($info['number_unformatted'])) {
    $info['number_unformatted']['field_types'][] = 'arithmetic';
  }
}